modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/CraftingCraft/issues"

[[mods]]
modId="craftingcraft"
version="${mod_version}"
displayName="Crafting Slots"
displayURL="https://mods.twelveiterations.com/mc/craftingslots"
logoFile="craftingcraft-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Adds an inventory crafting table and a normal portable one.
'''

[[dependencies.craftingcraft]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.craftingcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.craftingcraft]]
    modId="balm"
    mandatory=true
    versionRange="${balm_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.craftingcraft]]
    modId="craftingtweaks"
    mandatory=false
    versionRange="[16,)"
    ordering="NONE"
    side="BOTH"